padel=read.csv("descriptors_padel_fda.csv")
padelpol=read.csv("descriptors_padel_pol.csv")
mordred=read.csv("descriptors_mordred_fda.csv")
mordredpol=read.csv("descriptors_mordred_pol.csv")
print(padel)
