channels:
  - kotori_y
  - conda-forge
  - r
dependencies:
  - rdkit
  - dimorphite-dl
  - padelpy
  - scopy
  - pandas
  - matplotlib
  - scipy
  - mordred
  - numpy==1.19
  - r-essentials
  - r-caret
  - r-cubist
